CC=gcc

all: first second third

first:	first_answer.c
	$(CC) first_answer.c -o first_answer

second:	second_answer.c
	$(CC) second_answer.c -o second_answer

third:	third_answer.c
	$(CC) third_answer.c -o third_answer
